DROP TABLE "CITIES" cascade constraints;
DROP TABLE "EMPLOYMENT_TYPE" cascade constraints;
DROP TABLE "JOB_ASSIGNMENT" cascade constraints;
DROP TABLE"JOB_STATUS" cascade constraints;
DROP TABLE "JOBS" cascade constraints;
DROP TABLE "MESSAGES" cascade constraints;
DROP TABLE "PAGE_VISITED" cascade constraints;
DROP TABLE "PROFILE" cascade constraints;
DROP TABLE "PROPOSED_TECHNOLOGIES" cascade constraints;
DROP TABLE "ROLE_USER" cascade constraints;
DROP TABLE "STATES" cascade constraints;
DROP TABLE "TECHNOLOGIES" cascade constraints;
DROP TABLE "TESTDATE" cascade constraints;
DROP TABLE "USER_STORY" cascade constraints;
DROP TABLE "USERS" cascade constraints;